### ISSUE TITLE
Random crashes.

### ISSUE THREAD

**Issue by TheGuyWhoo** [timothyschoen/PlugData#79] opened 2022-05-02 13:06 UTC
So I've been able to reproduce this in both reaper 6.44 and carla(I think the version before the recent update), linux mint 64 bit.

When I load pure data in carla I get this in the logs:
  
JUCE Assertion failure in juce_Desktop.cpp:108
JUCE Assertion failure in juce_Desktop.cpp:108
JUCE Assertion failure in juce_AudioProcessor.cpp:365

To reproduce the crash, load a receive param1 by clicking the + button, add a bang and an [openpanel] and connect them, and then add an object and try to load an abstraction using the suggest feature when you type in an object. Sometimes this causes a crash. I don't know how related any of this is, this is just what I've done to cause a crash so far.

**Comment by timothyschoen** [comment] 2022-05-02 15:04
Thanks for reporting! I appreciate that you took the time to figure out how exactly to trigger a very specific bug, that's super helpful! I'll look into it soon!

**Comment by TheGuyWhoo** [comment] 2022-05-02 22:21
No trouble! If you can't get it to crash try closing the daw and repeating the process a few times.

**Comment by timothyschoen** [comment] 2022-05-02 22:22
Ah thanks, I was trying on Mac first, no problems so far. I'll try it on linux now!

**Comment by TheGuyWhoo** [comment] 2022-05-02 22:52
Okay so closing the daw is not necessary. Go through all the steps I mention, but click on the bang and leave the window open in the background, and move the parameter around. Then keep loading and deleting an abstraction and it should cause a crash.

**Comment by timothyschoen** [comment] 2022-05-02 22:54
Ah, so I need to actually click the bang -> openpanel, I missed that.

**Comment by timothyschoen** [comment] 2022-05-03 00:15
I got the crash! I believe that running it in release mode fixes this problem (to do this, add ```-DCMAKE_BUILD_TYPE=Release``` at the end of your cmake command, you'll get much better performance as well!)  It's still good to find out what's triggering the assertion though.

**Comment by timothyschoen** [comment] 2022-05-04 11:54
I wonder, does building in release mode fix this crash for you?

**Comment by TheGuyWhoo** [comment] 2022-05-04 12:00
Currently in the process of building, sorry for the wait!

**Comment by TheGuyWhoo** [comment] 2022-05-04 13:11
So I was previously using binaries from the actions tab. Just built it for the first time and it built succesfully, but I get a segmentation fault(core dumped) when I try to run the standalone and an immediate crash when I try to load the plugins in carla. In reaper they load the first time but crash if you remove them and try to load them again. I also still get the crash when I try to load an abstaction, it seems all the other steps are unnecessary and you only have to load an abstraction a few times. Also the lv2 didn't generate propperly, It's only the .so and the lv2_file_generator in the folder.

**Comment by timothyschoen** [comment] 2022-05-04 13:38
Yeah I noticed this crash, must be a recent change. Working on a fix right now. I didn't even know everyone has access to actions build, is this new? I like it! But one thing that's strange here is that you're getting assertions in that build, that build should be in release mode! So you may have uncovered a problem here!

You have to generate the lv2 yourself unfortuntately, here's a shell script to package the lv2 for Mac and Linux. On Windows it could possibly work with minGW.


From PlugData's root directory, do:
```
mkdir ./Plugins/LV2/PlugData.lv2

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
./Plugins/LV2/lv2_file_generator ./Plugins/LV2/PlugData_LV2.so PlugData
mv ./Plugins/LV2/PlugData_LV2.so ./Plugins/LV2/PlugData.lv2/PlugData.so
elif [[ "$OSTYPE" == "darwin"* ]]; then
./Plugins/LV2/lv2_file_generator ./Plugins/LV2/PlugData_LV2.dylib PlugData
mv ./Plugins/LV2/PlugData_LV2.dylib ./Plugins/LV2/PlugData.lv2/PlugData.dylib
else
./Plugins/LV2/lv2_file_generator ./Plugins/LV2/PlugData_LV2.dll PlugData
mv ./Plugins/LV2/PlugData_LV2.dll ./Plugins/LV2/PlugData.lv2/PlugData.dll
fi

mv manifest.ttl ./Plugins//LV2/PlugData.lv2/manifest.ttl
mv presets.ttl ./Plugins//LV2/PlugData.lv2/presets.ttl
mv PlugData.ttl ./Plugins//LV2/PlugData.lv2/PlugData.ttl
```

**Comment by TheGuyWhoo** [comment] 2022-05-04 14:31
Okay so I just checked the lv2 and it's causing the same behavior as the vst3.

**Comment by TheGuyWhoo** [comment] 2022-05-04 15:58
The standalone throws

segmentation fault(core dumped)

when I try to run it.

**Comment by timothyschoen** [comment] 2022-05-04 16:00
Does this still happen after ec030c3187cb7838e9ce11e9f4e20cd288b13a14?

**Comment by timothyschoen** [comment] 2022-05-04 17:38
I've had some lagginess in the standalone before as well, I'll see where that comes from. I'll look into the assertions too.

I think that it's no problem if it uses X11 right? Isn't that kinda expected? I couldn't imagine a reason why they would let you know that, except maybe when you're using wayland?

**Comment by TheGuyWhoo** [comment] 2022-05-04 17:44
Trying to use an abstraction that has unsupported objected causes a freeze and 100% cpu usage, happens on all plugins. Does not happen in standalone.

I'm on X11 I think(after a brief search to see what wavyland is haha, I'm using vanilla linux mint 20), but I don't think it's a problem, does seem to be causing issues.

**Comment by timothyschoen** [comment] 2022-05-04 17:45
Nice catch, I'll check that out.

I've seen some issues using the LV2 plugins as well, sometimes is resizes randomly... I'd recommend using the VST on Linux for now as it appears to be more stable.

**Comment by TheGuyWhoo** [comment] 2022-05-04 17:45
Does not I mean in case you miss the edit.

**Comment by timothyschoen** [comment] 2022-05-04 18:08
You are building in release mode now right? Because if you aren't, that'll make the standalone slow for sure.

**Comment by timothyschoen** [comment] 2022-05-04 19:34
> Trying to use an abstraction that has unsupported objects causes a freeze and 100% cpu usage

I'm trying to reproduce this in Reaper on Ubuntu, but this is not happening for me. By an invalid object, do you just mean a non-existent object, like some random text?

**Comment by TheGuyWhoo** [comment] 2022-05-04 21:22
https://gist.github.com/lzref/00ed916783fa33d5cc52

This is the patch causing the crash. Maybe I am wrong about why it happens.

Yes, this was from the actions tab again.

**Comment by timothyschoen** [comment] 2022-05-04 21:40
Thanks that'll help! I'm also really curious if pd drag-and-drop examples will work in PlugData yet, I'm guessing they won't?

**Comment by timothyschoen** [comment] 2022-05-04 21:45
I see there's some other bug when using this patch: it spams the console very quickly, which is probably why it freezes. I should probably make it so that lots of console messages don't freeze PlugData though.

**Comment by TheGuyWhoo** [comment] 2022-05-04 21:54
I'm unsure, I don't really know how to set it up and don't have the externals needed in that patch yet. It would be a very cool feature though. Linux is kind of light on samplers and plugdata could provide a very handy stop gap for that. Even if it's just able to capture the file path in a message object I could make my own sampler with drag and drop capability and complex envelopes, etc. Right now the only decent working sampler I know of is shortcircuit 1, but it's quite old and doesn't support drag and drop.

**Comment by timothyschoen** [comment] 2022-05-05 02:49
I found out what caused the crash: It was because it uses pd's drawtext object. I support pd drawing with drawpolygon and such, so it tried to handle drawtext with that mechanism and crashed. Should. be fixed! And since your earlier issue is also resolved, I'll close this report!

**Closed by timothyschoen** 2022-05-05 02:49 UTC
