### ISSUE TITLE
Glitchy Audio Ubuntu 20.04

### ISSUE THREAD

**Issue by jimruxton** [timothyschoen/PlugData#74] opened 2022-04-26 15:55 UTC
Hi I'm trying out PlugData for the first time. I just tried playing a simple tone in standalone mode osc~ into dac~ . The audio is glitchy. I'm using the same settings as PD Vanilla which sounds fine. I'm using Pulse audio with a 44100 Hz sampling rate and 1024 bits. Wondering why the difference could be happening. Looks like a super exciting project. Thanks for this.

**Comment by timothyschoen** [comment] 2022-04-26 17:56
I can reproduce this, so I'll have it fixed soon!

**Comment by jimruxton** [comment] 2022-04-26 18:41
Thanks for looking into this.

**Comment by timothyschoen** [comment] 2022-04-30 00:48
The crazy thing is, when I use jack it works fine, but with PulseAudio it's a glitchy mess. I see a few other people on the JUCE forum are suffering from this, I'm not sure if I'll be able to fix this. I'll leave the issue open in case anyone has any ideas.

The best solution here is to either use jack, or run PlugData inside a DAW.

**Comment by KottV** [comment] 2022-05-04 11:43
Hi,

JUCE apps never worked via PulseAudio well. So you have to use JACK or ALSA (without PA).

**Comment by timothyschoen** [comment] 2022-05-04 11:45
It's a shame, but apparently PulseAudio wasn't made for production audio, so you're better off using Jack or ALSA anyways. Guess I'll close this because there's nothing I can do about it :(

**Closed** 2022-05-04 11:45 UTC
Labels: bug, wontfix
