### ISSUE TITLE
MSYS / MinGW 

### ISSUE THREAD

**Issue by btvd** [timothyschoen/PlugData#4] opened 2022-01-05 17:15 UTC
Could not compile VST in WIn10 with MSYS / MinGW. Any advices how yo do it right?

**Comment by timothyschoen** [comment] 2022-01-05 17:21
I still have to test it for minGW, but it should work when using Visual Studio 2019. My last build on windows was a few commits ago (before I restructured the cmake project), so I'll check if it still builds in minute!

If you have Visual Studio installed, run `cmake -G "Visual Studio 16 2019" ..`

**Comment by Adv0c4tus** [comment] 2022-01-05 17:46
> I still have to test it for minGW, but it should work when using Visual Studio 2019. My last build on windows was a few commits ago (before I restructured the cmake project), so I'll check if it still builds in minute!
> 
> If you have Visual Studio installed, run `cmake -G "Visual Studio 16 2019" ..`

The problem is that I do not have it, so i've tried to use other installed buildtools... I use VS Code as IDE and MSYS/MinGW as toolchain provider

**Comment by Adv0c4tus** [comment] 2022-01-05 17:48
I can provide more information about errors I see while using MSYS / MinGW or any helpfull information that you need to fix it ))) I really want to use Pd as VST in Bitwig)))

**Comment by timothyschoen** [comment] 2022-01-05 18:46
You could try the prebuilt version here: https://github.com/timothyschoen/PlugData/releases/tag/v0.1
Do keep in mind that there might be some bugs, it's a relatively new project so it's not a perfect solution yet.

I don't have any experience building JUCE projects with MinGW, so I'll dive into that later this week.

**Comment by Adv0c4tus** [comment] 2022-01-05 19:54
Thank's! Will wait for more info later!

**Comment by Adv0c4tus** [comment] 2022-01-05 20:07
> You could try the prebuilt version here: https://github.com/timothyschoen/PlugData/releases/tag/v0.1 Do keep in mind that there might be some bugs, it's a relatively new project so it's not a perfect solution yet.
> 
> I don't have any experience building JUCE projects with MinGW, so I'll dive into that later this week.

I've tested vst3, Bitwig 4.0.1 does not see it :(((

**Comment by timothyschoen** [comment] 2022-01-05 21:47
I've seen this problem before on Windows, I'll fix it tomorrow!

**Comment by btvd** [comment] 2022-01-05 22:52
I found something, but don't know if it could help you https://github.com/McMartin/FRUT#documentation

**Comment by timothyschoen** [comment] 2022-01-06 17:55
I use the cmake build system from Camomile, I think that it could work for MinGW as well, the problem right now is that I probably need to link pthreads correctly. I didn't get to it today because I'm finding more bugs than I hoped to... but it's high on the list to get the VSTs to at least appear on Windows.

**Comment by btvd** [comment] 2022-01-06 20:49
> I use the cmake build system from Camomile, I think that it could work for MinGW as well, the problem right now is that I probably need to link pthreads differently for MinGW. I didn't get to it today because I'm finding more bugs than I hoped to... but it's high on the list to get the VSTs to at least appear on Windows.

Thanks! If you need any help with testing - I'm in!

**Comment by btvd** [comment] 2022-01-08 10:26
Will you make new realese for test?

**Comment by timothyschoen** [comment] 2022-01-08 12:23
I'm releasing a new version today, unfortunately I haven't been able to reproduce this bug myself, but I've about it from multiple people. If it's still not fixed in this release, It'll be the first thing I'll be working on.

If it still doesn't work, I'm curious if it works in Reaper for you

**Comment by timothyschoen** [comment] 2022-02-06 03:20
Closing because VSTs are appearing on Windows now, and MSYS/MinGW support is not a priority when it works with msbuild/Visual Studio

**Closed by timothyschoen** 2022-02-06 03:20 UTC
