### ISSUE TITLE
VST works but standalone doesn't 

### ISSUE THREAD

**Issue by carlca** [timothyschoen/PlugData#2] opened 2022-01-03 19:48 UTC
* Mac Mini M1
* macOS 12.1 Monterey
* Bitwig Studio 4.1.2

I've build the package from the Git clone, and installed the standalone and the VST. If I try to run the standalone, the tray icon dances around a bit indicating some sort of activity, then it stops, but no GUI appears on the screen. Also, PlugData does not appear in the top menu. Alt-Tabbing reveals PlugData as an active app, but "Show All Windows" from the tray icon reveals nothing.

The VST in Bitwig Studio appears to work as expected, although the plugin did crash on me after a few minutes activity. I have yet to uncover the extent of this problem. If it happens agin, I'll try to get a crash dump of some kind.

**Comment by timothyschoen** [comment] 2022-01-03 21:28
Thanks for testing and reporting! I will investigate this soon, I'm on Monterey on M1 myself so I'm surprised it doesn't work. Possibly it can't initialise because it's not allowed to access the filesystem? If you could build and debug in Xcode and tell me where it hangs, that would help a lot!

**Comment by carlca** [comment] 2022-01-03 21:44
I'm happy to try the Xcode thing. What project do I load into Xcode?

**Comment by timothyschoen** [comment] 2022-01-03 21:52
I'm able to reproduce the hanging standalone issue by running it on another MacBook, so I think I'll be able to figure it out! I'll also try running the VST in Bitwig, I've currently tested it mostly in Reaper and Logic.

If you want to investigate it in Xcode, I'd recommend running

`cmake -DCMAKE_BUILD_TYPE=Debug -G Xcode ..`

Then open the generated project and run the Standalone.

**Comment by carlca** [comment] 2022-01-03 21:59
I'm running `cmake -DCMAKE_BUILD_TYPE=Debug -G Xcode ..` from the Build folder, and getting this message...
```
CMake Error: Error: generator : Xcode
Does not match the generator used previously: Unix Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
```
Any ideas?

**Comment by timothyschoen** [comment] 2022-01-03 22:00
Oh sorry, forgot to mention, you need to empty out the build folder first.

**Comment by carlca** [comment] 2022-01-03 22:08
All I'm getting when I try to debug PlugData is this small message...
![Screenshot 2022-01-03 at 22 07 05](https://user-images.githubusercontent.com/260612/147985714-34f97adf-d2b1-478d-b1ee-e06bff8d24a3.png)

**Comment by carlca** [comment] 2022-01-03 22:10
I'm a little out of my depth here. Perhaps I'll let you carry on with this, as you seem to know what you are doing 😉

**Comment by timothyschoen** [comment] 2022-01-03 22:11
Thanks for the information, I think I can figure it out from here! I'll let you know when it's fixed

**Comment by carlca** [comment] 2022-01-03 22:16
Cool! Thanks for your help, and thanks for the app itself. 

You know I mentioned the VST crashing. It's done it again. I got these two Bitwig messages. It seems to happen after a period of zero activity after about 15 minutes or so.

![Screenshot 2022-01-03 at 22 14 52](https://user-images.githubusercontent.com/260612/147986317-1c088c60-78ef-460c-8680-43911d633cb3.png)

**Comment by timothyschoen** [comment] 2022-01-03 23:10
That's useful, I'll try to replicate this. Looks like a deadlock...

The other bug is also caused by some sort of deadlock immediately after starting up, which is strange. It doesn't happen in an older version so it should be fixable.

**Comment by timothyschoen** [comment] 2022-01-03 23:28
I think I solved it the standalone issue! It was caused by the audio settings dialog trying to load before the audio was ready. Could you pull the changed and see if it works now?

**Comment by timothyschoen** [comment] 2022-01-04 01:11
I've also found the reason for the crashes in Bitwig, the same thing happened in some other DAWs. It should be fixed now, if you can confirm it I'll close the issue.

**Comment by carlca** [comment] 2022-01-04 17:22
Sorry for the delay. I've rebuilt everything and the Standalone and the VST all seem to work.
However, one slight change has occurred which may be my mistake, but I don't know. I tried to recreate the second of the example screenshots. When I did this last night, the app worked and appeared to reason to Mouse Move events. Now, when I do this it is responding to Mouse Down and Mouse Up click events. here is the `pd`,,,

```
#N canvas 827 239 527 327 12;
#X obj 93 41 mouse;
#X obj 58 114 changed;
#X obj 80 176 print Hello World;
#X connect 0 0 1 0;
#X connect 1 0 2 0;
``` 


As far as I can tell, this is exactly the same test script that I created last night. 
Your thoughts?

**Comment by carlca** [comment] 2022-01-04 17:50
Aha! It was my mistake. Last night I had the cable connected to the middle port, whereas just now I used the left hand port. Time for me to RTFM, I think 😉

**Comment by timothyschoen** [comment] 2022-01-04 20:28
Thanks for reporting these bugs, it would've taken me a while to find them myself!

**Closed by timothyschoen** 2022-01-04 20:28 UTC

**Comment by carlca** [comment] 2022-01-04 21:55
Thanks for putting the package together! It adds yet another string to my bow 😉
