### ISSUE TITLE
Wave doesn't display in array.

### ISSUE THREAD

**Issue by TheGuyWhoo** [timothyschoen/PlugData#82] opened 2022-05-05 12:47 UTC
Previously it did, but in [5dc05ea](https://github.com/timothyschoen/PlugData/commit/5dc05ea8cf5d7a7d19a20886df8587ac3f5b41ee) it doesn't.

Also as you mentioned lv2 is quite laggy, and while vsts are better with more objects it get laggier. It seems to mostly be in regards to selection, connecting objects, panning the view around, and moving objects. But adjusting values and actually adding objects isn't laggy at all, just manipulating their position on the canvas.

**Comment by timothyschoen** [comment] 2022-05-05 12:52
Unfortunately JUCE's graphics are not very fast, I'm trying to optimise it as much as I can, but there's still some progress to be made. Moving lots of objects is especially slow right now... Currently I'm buffering a lot of stuff to images, just to prevent having to redraw it when objects move through its bounds.

This is why I attempted to get nanovg working with JUCE [here](https://github.com/timothyschoen/juce_nanovg) but unfortunately I don't know enough about it to make it work (and actually be fast).

I'm wondering if that is the cause for waves not drawing though?

**Comment by TheGuyWhoo** [comment] 2022-05-05 13:56
Hmm, I'm not sure. In which update did you make the change? I'll download the binaries before that update and check if it's the same.

**Comment by timothyschoen** [comment] 2022-05-05 13:59
I don't use juce_nanovg in PlugData, it's not anywhere near finished yet. And I didn't make any significant changes to drawing recently either, I see now that that was unclear in my last comment. So it's a total mystery to me that this used to work for you but doesn't, I've actually seen it being broken before though.

**Comment by TheGuyWhoo** [comment] 2022-05-05 14:20
Oh okay I see! In the meantime it's not a very big deal, I just use purr data to patch and then I can use the patch in plugdata.

**Comment by TheGuyWhoo** [comment] 2022-05-05 17:37
Length of the file seems to matter! If you load short samples like kicks etc. it actually shows up in array.

**Comment by timothyschoen** [comment] 2022-05-05 17:38
Nice, I'll start testing why this happens soon!

**Comment by timothyschoen** [comment] 2022-05-15 01:35
![Screen Recording 2022-05-15 at 03 32 51](https://user-images.githubusercontent.com/44585538/168453560-ba7bb053-8e28-4d9b-b08c-b5d32cea343b.gif)

I've made a big improvement to the array, it should work much better now. I'm hoping this fixes your problem as well.

**Comment by timothyschoen** [comment] 2022-05-19 00:53
Problem is presumably fixed, feel free to reopen if it isn't

**Comment by TheGuyWhoo** [comment] 2022-05-21 15:38
Very sorry for the silence, been having issues with my internet. I tried to test it, but there are some issues with the UI. I included a screenshot in the issue I just made.

**Comment by timothyschoen** [comment] 2022-05-21 15:59
No need to apologise, we're all volunteering here, I don't expect anything and am grateful for everything ;)

UI issues should be fixed!

**Comment by TheGuyWhoo** [comment] 2022-05-22 09:14
Array is still only working for me for smaller files, present in all plugins and standalone.

Carla log for lv2(this is when I load the ui, not when the plugin itself is loaded):

    Carla assertion failure: "index != LV2UI_INVALID_PORT_INDEX" in file CarlaPluginLV2.cpp, line 6146

And for the vsts it's just the assertion failure stuff:

    JUCE Assertion failure in juce_Desktop.cpp:108
    JUCE Assertion failure in juce_Desktop.cpp:108
    JUCE Assertion failure in juce_AudioProcessor.cpp:365

Unfortunately not a lot of information that I can provide. If there is a way to get more information about what is happening I'd be willing to try that.

**Comment by timothyschoen** [comment] 2022-06-24 23:30
Sorry, I must have missed this! I think I've found the cause for arrays not showing the whole wave shapes. There was a problem with programatically resizing arrays, should be fixed now!

Very large files may still struggle with performance issues, which is something I'm currently working on

**Comment by timothyschoen** [comment] 2022-06-28 11:22
Array should work properly now!

**Closed by timothyschoen** 2022-06-28 11:22 UTC
