### ISSUE TITLE
Having the parameter window open consumes quite a bit of CPU.

### ISSUE THREAD

**Issue by TheGuyWhoo** [timothyschoen/PlugData#84] opened 2022-05-06 10:21 UTC
Having it open seems to use up a lot of resources, until you close it then it settles back down to normal. I'm using the latest build from the action tab [64a08ed](https://github.com/timothyschoen/PlugData/commit/64a08ed180b8779bcd05c25982dd0aa1a29a5a0e)

**Comment by timothyschoen** [comment] 2022-05-06 12:20
Hmm so you can't download externals from settings in reaper if I understand correctly? I could disable the panel to prevent confusion, since externals won't work in the plugin anyway? It should download/install them correctly anyway though...

**Comment by FlachyJoe** [comment] 2022-05-06 12:31
> since externals won't work in the plugin anyway

Full pd externals ( i.e. those which only contains abstractions ) should work, only C-coded ones fail. For example list-abs is deken-installable and has no C stuff.

**Comment by TheGuyWhoo** [comment] 2022-05-06 12:38
No from the standalone. The bit about reaper is in regards to the slider panel causing a higher cpu load, that doesn't happen in carla.

Sorry for the confusion!

**Comment by timothyschoen** [comment] 2022-05-06 18:57
No problem I get it now! Weird that installing externals doesn't work though, you're on Mac right?

@FlachyJoe I didn't even consider that! I'll keep the downloader in the plug-in then.

**Comment by TheGuyWhoo** [comment] 2022-05-06 21:56
No I'm on linux mint 20.

**Comment by timothyschoen** [comment] 2022-05-06 22:02
I've only tested Linux on ARM so far, maybe it's not correctly reading the architecture for x86/x64... Are you getting no results when searching, or does installing packages not work properly?

**Comment by TheGuyWhoo** [comment] 2022-05-06 22:23
I'm getting no results, just the loading icon in the search bar, but other than that nothing happens

**Comment by timothyschoen** [comment] 2022-05-07 14:03
I can reproduce this in a Linux Mint VM, fix coming soon!

**Comment by timothyschoen** [comment] 2022-05-07 19:26
fixed!

**Comment by TheGuyWhoo** [comment] 2022-05-07 22:53
Nice, thanks!

**Comment by TheGuyWhoo** [comment] 2022-05-07 22:53
Whoops accidentally hit close again. Sorry!

**Comment by timothyschoen** [comment] 2022-05-30 01:59
Should be fixed, I've optimised it a lot. I might still optimise a bit more, but it's already a lot better than before!

**Closed by timothyschoen** 2022-05-30 01:59 UTC
