### ISSUE TITLE
Subpatch crash

### ISSUE THREAD

**Issue by plantappreciator** [timothyschoen/PlugData#97] opened 2022-05-11 00:27 UTC
When I delete an outlet of a subpatch that is connected to another object, the standalone program and the plugin crashes when I go back to the main patch. 

The only error message is Segmentation fault: 11, though I also get 
"JUCE Assertion failure in juce_ApplicationCommandTarget.cpp:71
JUCE Assertion failure in juce_ApplicationCommandTarget.cpp:150" 
anytime I save; probably unrelated.

I'm using a 2021 Macbook (ARM64), macos 12.3.1

<img width="180" alt="Screen Shot 2022-05-10 at 8 07 22 PM" src="https://user-images.githubusercontent.com/103082019/167744367-90fe8fdc-7480-41d3-b503-815150cdccab.png">
<img width="186" alt="Screen Shot 2022-05-10 at 7 56 49 PM" src="https://user-images.githubusercontent.com/103082019/167744430-48591ec7-1df9-476c-b7d7-70851dfef107.png">
<img width="193" alt="Screen Shot 2022-05-10 at 8 21 06 PM" src="https://user-images.githubusercontent.com/103082019/167744924-9d233e4d-e826-4e1a-929d-37c167fe797c.png">

Example patch:
#N canvas 0 22 450 300 test 1;
#N canvas 0 22 450 278 (subpatch) 0;
#X text 0 0 plugdatainfo <?xml version="1.0" encoding="UTF-8"?> <PlugDataInfo/>;
#X coords 0 1 100 -1 1 1 1;
#X restore 0 0 graph;
#X obj 299 145 inlet;
#X obj 302 204 outlet;
#X connect 1 0 2 0;
#X restore 291 212 pd test;
#X obj 295 262 *;
#X connect 0 0 1 0;

Also thank you so much for this project!! I'll use it a lot and share more bugs in the future.

**Comment by timothyschoen** [comment] 2022-05-11 00:29
The save message is another bug that I noticed, but it's probably unrelated.

I can reproduce this bug, should be fixed soon. Thanks for reporting!!

**Comment by timothyschoen** [comment] 2022-05-11 23:06
Is this the result you're getting when typing inlet~ and outlet~? Because I get something different (excuse the new colour scheme):

<img width="179" alt="Screenshot 2022-05-12 at 01 04 58" src="https://user-images.githubusercontent.com/44585538/167961484-c0883e12-0ab7-4859-ac44-b074cfa0ebd1.png">

which matches pd:

<img width="179" alt="Screenshot 2022-05-12 at 01 05 12" src="https://user-images.githubusercontent.com/44585538/167961511-fbc7d4fa-e338-4f24-a37b-17aaa1570d4a.png">


Is it consistently getting this wrong or occasionally?

**Comment by timothyschoen** [comment] 2022-05-11 23:06
Crash should be fixed btw!

**Comment by timothyschoen** [comment] 2022-05-11 23:15
Cmd-S issue is also fixed

**Comment by alfonso73** [comment] 2022-05-12 08:18
> @alfonso73 Is this the result you're getting when typing inlet~ and outlet~? Because I get something different (excuse the new colour scheme):
> 
> <img alt="Screenshot 2022-05-12 at 01 04 58" width="179" src="https://user-images.githubusercontent.com/44585538/167961484-c0883e12-0ab7-4859-ac44-b074cfa0ebd1.png">
> 
> which matches pd:
> 
> <img alt="Screenshot 2022-05-12 at 01 05 12" width="179" src="https://user-images.githubusercontent.com/44585538/167961511-fbc7d4fa-e338-4f24-a37b-17aaa1570d4a.png">
> 
> Is it consistently getting this wrong or occasionally?

Crash fixed! 
This is what i have with latest build downloaded from action tab....everything seems fine.
<img width="558" alt="inlet~ and outlet~_fixed" src="https://user-images.githubusercontent.com/3230434/168025013-681120a5-9e2b-4b02-b0f8-470976a29f77.png">

**Comment by timothyschoen** [comment] 2022-05-12 10:59
Well guess it's fixed then!

**Closed by timothyschoen** 2022-05-12 10:59 UTC
