### ISSUE TITLE
Gui Standalone in v.0.5 is faster than v.0.5.1!

### ISSUE THREAD

**Issue by charlesneimog** [timothyschoen/PlugData#86] opened 2022-05-08 01:43 UTC
Hello Tim, congrats for all your work! 

I have noted that the standalone v.0.5 is very much more fast and fluid (GUI part) that the v.0.5.1.  

I know that the standalone part seems not to be the priority, but would be great if it could be continue developed! 

Just reporting it! 

I am on Windows 11!

Thanks!

**Comment by timothyschoen** [comment] 2022-05-08 01:52
I actually test a lot in the standalone because it's easier to debug that way! I did mess with some graphics rendering stuff, I might've accidentally made it worse instead of better... On top of that, there might be slight differences

Another thing is that it updates GUI objects more frequently, the change messages used to be grouped together every 20ms, now it's every 5ms. This does make things more responsive, but also slower when there is a lot going on.

The larger problem here is that JUCE's graphics are not super fast and not GPU accelerated, meaning I have to optimise a lot. Especially everything on the canvas needs to be very efficient because patches can get very large.

**Comment by timothyschoen** [comment] 2022-05-08 02:58
This might be windows specific, I did some profiling on macOS and it seems fine...

**Comment by timothyschoen** [comment] 2022-05-08 12:10
I can reproduce this as well, it's a very big difference :(

I'm going to create a patch release quickly fixing this and some other problems!

**Comment by charlesneimog** [comment] 2022-05-08 15:17
> I actually test a lot in the standalone because it's easier to debug that way! I did mess with some graphics rendering stuff, I might've accidentally made it worse instead of better...

Great!! :)

> I'm going to create a patch release quickly fixing this and some other problems!

Thank you!!

**Comment by timothyschoen** [comment] 2022-05-09 12:12
Commit 5187d03 appears to be the cause.

**Comment by timothyschoen** [comment] 2022-05-09 17:48
Fixed in the last commit!

**Closed by timothyschoen** 2022-05-09 17:48 UTC

**Comment by charlesneimog** [comment] 2022-05-09 18:26
Great, thank you! I will try to compile it!

**Comment by timothyschoen** [comment] 2022-05-09 18:57
I noticed it's faster, but still a little bit slower than v0.5...

I can make it even faster by enabling native window shadows, but it looks really ugly because it draws a rectangular shadow around the rounded window.

**Comment by charlesneimog** [comment] 2022-05-09 19:13
> Another thing is that it updates GUI objects more frequently, the change messages used to be grouped together every 20ms, now it's every 5ms. This does make things more responsive, but also slower when there is a lot going on.

About this, you don't think the frame fresh rate is much! Because, for example, in my notebook, I have a 60Hz screen. This means that it could draw (or change the pixel) each 16,6ms. So, in my understating this configuration are use 2x much CPU to process things that will not be exactly drawn.

I may have misunderstood!!

-------------------------

> I can make it even faster by enabling native window shadows, but it looks really ugly because it draws a rectangular shadow around the rounded window.

I like the way the it is now. :)

**Comment by timothyschoen** [comment] 2022-05-09 19:15
When I wrote this I immediately realised this! It refreshes at 16ms now.

**Comment by charlesneimog** [comment] 2022-05-09 19:16
Great!! Thanks!

**Comment by timothyschoen** [comment] 2022-05-09 19:46
I'm now drawing the shadow on each side from a pre-rendered image individually to prevent having to calculate the gradients, and also not paint the whole surface behind the window. Performance is back to normal now!

**Comment by charlesneimog** [comment] 2022-05-09 20:42
Hi, it is normal and with good (low) CPU consuming here.

**Comment by timothyschoen** [comment] 2022-05-09 20:54
Thanks for confirming!!
