### ISSUE TITLE
"..couldn't create param x" object while opening DAW save on plug in version

### ISSUE THREAD

**Issue by hAK-klang** [timothyschoen/PlugData#179] opened 2022-08-26 21:32 UTC
First of all... fantastic project!! Thanks so much for sharing.

I came across an issues with the parameter objects. 
Whenever I open a Daw save (in Reaper)  parameter objects are not loaded. 
error message "..couldn't create param x"
as a result all automations are not working.

when saved and and reopened as a pd patch using the save and open tabs within the plug in it works flawlessly.
![Screenshot 2022-08-26 at 23 30 58](https://user-images.githubusercontent.com/112208336/186993617-7166c0f1-80c2-41c8-90dc-ecc9257dcdaf.png)

**Comment by timothyschoen** [comment] 2022-08-26 21:40
Thanks! I've seen this problem before, I'm not sure yet how this happens. A temporary solution is to put the "param.pd" subpatch in the ```~/Library/PlugData/0.6.0/Abstractions``` folder. I've included it as an attachment. If you just want to receive automation, you can also add [r param1] to your patch, where you replace the 1 with the index you want.

[param.pd.zip](https://github.com/timothyschoen/PlugData/files/9436530/param.pd.zip)

**Comment by hAK-klang** [comment] 2022-08-26 22:09
Thanks for the quick reply and the suggested workarounds.
The "param.pd" subpatch in the abstraction folder hasn't been able to solve the problem.
However the [r param1] solution works totally fine for me.

**Comment by timothyschoen** [comment] 2022-08-27 13:42
That gives me a clue! Can you post a screenshot of this panel?

<img width="1054" alt="Screenshot 2022-08-27 at 15 40 40" src="https://user-images.githubusercontent.com/44585538/187032891-63185cc0-1d1a-40e8-b86f-565e4edbf921.png">

**Comment by hAK-klang** [comment] 2022-08-29 08:26
Sorry for the late reply. I've been away for the weekend.

As a side note.... I've been trying out different paths as well and made sure that the [param.pd] abstraction was always within the paths. However that didn't make a difference. Right now everything is back to default settings with [param.pd] in the ~/Library/PlugData/0.6.0/Abstractions folder.

![Screenshot 2022-08-29 at 10 15 03](https://user-images.githubusercontent.com/112208336/187156331-6aee045e-4f2b-4ef3-b02d-4cc89e396d56.png)
.

**Comment by timothyschoen** [comment] 2022-08-29 15:54
That is really strange! I can't reproduce this yet, but I've heard this from multple people now and would like to fix it.

**Comment by hAK-klang** [comment] 2022-08-30 10:18
It seems it's the same issue with all abstractions. I can create an abstraction object in the patcher without any problems while typing the abstraction name in an empty object. Saving and reloading the patch works fine too. However when reopening the DAW after a DAW save, abstractions won't load and I get the error message "...couldn't create"
I did some tests with my own abstractions and different search paths. Always the same problem. I also noticed the same thing happening while loading audiofiles (wav) using a loadbang into a "read" message. It can't find the wav files after reopening the DAW. "sound filer read: test.wav: No such file or directory". But it works OK when the patch is loaded from within the patcher. This problem however is fixable with delaying the bang for 2000ms with a delay object. Then the audiofile gets loaded when reopening the DAW. Don't know if this might be a clou?

If it is of any help :I am on a late 2012 Mac mini 2,6 GHz Intel Core i7 16GB ram, running macOS Mojave 10.14.6 and the latest version of Reaper v 6.66. PD Vanilla 0.51-3

**Comment by timothyschoen** [comment] 2022-08-30 18:58
Yes! I made a mistake: It loads the search paths after it's done parsing documentation files, which is why it takes some time for them to get loaded. It's fixed now! Thanks for figuring out what was causing this, it was very helpful.

If you want, you can try this Actions tab build: https://github.com/timothyschoen/PlugData/actions/runs/2957332843
That will fix this issue and a bunch of others.

**Closed** 2022-08-30 18:58 UTC
