### ISSUE TITLE
Crash when opening/closing help files

### ISSUE THREAD

**Issue by alfonso73** [timothyschoen/PlugData#9] opened 2022-01-07 15:27 UTC
Hi, if i open a project (i.e an help patch or any .pd files) and close it Reaper and Live just crash on Windows 10 (64bit)

**Comment by timothyschoen** [comment] 2022-01-07 17:48
Did you use the released version or a recent clone? I thought I had fixed this with 11e14fcff802000bec24c4f693d3b208a2e68418, if you're using a recent commit I'll have to investigate.

**Comment by alfonso73** [comment] 2022-01-07 20:22
Hi @timothyschoen. I'm using the last released version 0.1.

**Comment by timothyschoen** [comment] 2022-01-08 13:20
I've uploaded a new release, so this should be fixed. Let me know if it still happens or if you have any other problems

**Comment by alfonso73** [comment] 2022-01-09 11:43
Hi @timothyschoen. To me it seems still pretty unstable. Opening and/or closing help files for example totally crash Reaper that quits instantly. BTW i.e. osc~ help doesn't produce any sound. Than trying to open the tabread~ help file from the osc~ file totally crash Reaper that suddenly quits. Probably there'sw is something that doesn't stop the audio stream correctly when a patch is open/colsed. just guessing...

**Comment by timothyschoen** [comment] 2022-01-09 12:15
I'm sorry for these problems...  Help files are especially experimental, I'm aware that they don't have audio output currently. I can reproduce the crash when opening a help file from a help file (weird that I forgot to try that...)

The problem is that I build most of the structure for PlugData around the idea that there is 1 instance of pd running (subpatchers/abstractions can be opened on the same instance), this is also how Camomile works.

But this doesn't work for help files, because I'm opening an object that doesn't exist in the currently opened patch, so we have to create an auxiliary instance, which might break some stuff. I think it'd be better to try to add the help files to the current instance in some way.

**Comment by alfonso73** [comment] 2022-01-11 16:12
Hi @timothyschoen ...i still have crashes with help file opening/closing...

**Comment by timothyschoen** [comment] 2022-01-13 20:52
I can't seem to reproduce this, are there any specific help files where this occurs?

**Comment by alfonso73** [comment] 2022-02-04 10:22
Hi @timothyschoen, thanks for the latest 0.3!
I'm checking if it curesd this issue but the issue is still present.
If you open the help file for osc~ then you try to open from osc~ help file the help file for any other object my DAWs (Reaper and Live 11.1 are my main ones) just crash. Reaper doesn't give any message. Live report the warning i attach here. If i click "Ok" then it quits. 
<img width="332" alt="Screenshot 2022-02-04 111232" src="https://user-images.githubusercontent.com/3230434/152512740-466faf66-f198-4cf1-b45e-8c80dfaf29d3.png">

**Comment by alfonso73** [comment] 2022-02-04 10:27
Probably everything is related to PlugData not supporting multiple instances. If i open two different PlugData instances then try to just create an empty object in any of the two instances, everything crashes.

**Comment by timothyschoen** [comment] 2022-02-04 13:23
Thanks, that'll help me figure it out! This is definitely a big problem, and with all the other problems I've already had reported on v0.3, I suspect I'll have a v0.3.1 out soon to fix these issues.

**Comment by timothyschoen** [comment] 2022-02-04 21:41
It took me some time but I think I fixed it! Turns out, you can actually run multiple root patches in one pd instance... Which makes sense because that's what pd does! I'll commit it later tonight when I've tested it more thoroughly. Thanks for reporting!

**Comment by timothyschoen** [comment] 2022-02-06 02:17
I've fixed it! Help files now work within the same system as abstractions and subpatchers, which should make it much more stable (and cleaner in code as well). New release coming probably next week!

**Closed by timothyschoen** 2022-02-06 02:17 UTC

**Comment by alfonso73** [comment] 2022-02-06 11:08
That's great @timothyschoen ! Thanks
